package main

import (
	"Assignment/arrays"
	"Assignment/closures"
	"Assignment/constants"
	"Assignment/errors"
	"Assignment/forloop"
	"Assignment/functions"
	"Assignment/hello"
	"Assignment/ifelse"
	"Assignment/interfaces"
	"Assignment/maps"
	"Assignment/methods"
	"Assignment/multiplereturns"
	"Assignment/pointers"
	"Assignment/ranges"
	"Assignment/recursion"
	"Assignment/slices"
	"Assignment/structs"
	"Assignment/switchcase"
	"Assignment/vadiadicfuncs"
	"Assignment/values"
	"Assignment/variables"
	"fmt"
)

func main() {
	fmt.Println("--------------PrintHello--------------")
	hello.PrintHello()
	fmt.Println("--------------PrintValues-------------")
	values.PrintValues()
	fmt.Println("--------------PrintVariables-------------")
	variables.PrintVariables()
	fmt.Println("--------------PrintConstants-------------")
	constants.PrintConstants()
	fmt.Println("--------------PrintForloop-------------")
	forloop.PrintForloop()
	fmt.Println("--------------PrintIfelse-------------")
	ifelse.PrintIfelse()
	fmt.Println("--------------PrintSwitch-------------")
	switchcase.PrintSwitch()
	fmt.Println("--------------PrintArrays-------------")
	arrays.PrintArrays()
	fmt.Println("--------------PrintSlices-------------")
	slices.PrintSlices()
	fmt.Println("--------------PrintMaps-------------")
	maps.PrintMaps()
	fmt.Println("--------------PrintRange-------------")
	ranges.PrintRange()
	fmt.Println("--------------PrintFunctions-------------")
	functions.PrintFunctions()
	fmt.Println("--------------PrintMultiple-------------")
	multiplereturns.PrintMultiple()
	fmt.Println("--------------PrintVariadic-------------")
	vadiadicfuncs.PrintVariadic()
	fmt.Println("--------------PrintClosures-------------")
	closures.PrintClosures()
	fmt.Println("--------------PrintRecursion-------------")
	recursion.PrintRecursion()
	fmt.Println("--------------PrintPointers-------------")
	pointers.PrintPointers()
	fmt.Println("--------------PrintStructs-------------")
	structs.PrintStructs()
	fmt.Println("--------------PrintMethods-------------")
	methods.PrintMethods()
	fmt.Println("--------------PrintInterfaces-------------")
	interfaces.PrintInterfaces()
	fmt.Println("--------------PrintErrors-------------")
	errors.PrintErrors()
}
